version: '3'

services:
  pqai_index:
    image: pqai_index
    container_name: pqai_index
    build: .
    restart: always
    volumes:
      - type: bind
        source: ./indexes
        target: /app/indexes
    ports:
      - ${PORT}:80
    environment:
      - USE_FAISS_INDEXES=${USE_FAISS_INDEXES}
      - USE_ANNOY_INDEXES=${USE_ANNOY_INDEXES}
      - PORT=${PORT}
